global:
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'default'

receivers:
  - name: 'default'
    email_configs:
      - to: ''               # ← TU EMAIL AQUI
        from: ''
        smarthost: ''
        auth_username: ''
        auth_password: ''
        send_resolved: true

    slack_configs:
      - api_url: ''          # ← TU SLACK WEBHOOK AQUI
        channel: '#alertas'
        send_resolved: true

    webhook_configs:
      - url: ''              # ← TU MICROSOFT TEAMS WEBHOOK AQUI
        send_resolved: true
