version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
  build:
    commands:
      - echo "Building Docker image"
      - docker build -t pentaho-exporter ./services/exporter
      - docker tag pentaho-exporter:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/pentaho-exporter:latest
      - $(aws ecr get-login --no-include-email --region $AWS_REGION)
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/pentaho-exporter:latest
artifacts:
  files: '**/*'
